version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/geotiff/geotiff-front
      - /home/geotiff/geotiff-front/node_modules
    command: bash -c "npm run start-on-server"
